---
run:
  concurrency: 4

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - depguard
    - errorlint
    - errname
    - exhaustive
    - exportloopref
    - gocritic
    - godot
    - gofmt
    - gosec
    - misspell
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - tparallel
    - unparam
    - whitespace

linters-settings:
  depguard:
    rules:
      main:
        files:
          - "$all"
          - "!$test"
          - "!**/pkg/secrets/keepertest/*.go"
        allow:
          - "$gostd"
          - github.com/ansd/lastpass-go
          - github.com/gobwas/glob
          - github.com/golang
          - github.com/gopasspw/pinentry
          - github.com/mitchellh/mapstructure
          - github.com/mitchellh/go-homedir
          - github.com/oklog/ulid
          - github.com/spf13/cobra
          - github.com/spf13/pflag
          - github.com/tobischo/gokeepasslib
          - github.com/zalando/go-keyring
          - github.com/zostay

      tests:
        files:
          - "$test"
          - "**/pkg/secrets/keepertest/*.go"
        allow:
          - "$gostd"
          - github.com/stretchr/testify
          - github.com/zostay
          - github.com/ansd/lastpass-go
